spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    password: 1488
    username: postgres
  flyway:
    baseline-on-migrate: true
jwt:
  token:
    secret : NorthSideWhiteWorldWide1488RunarGallGoildiSkaldhakkerSavager
    expired : 3600000
logging:
  level:
    org.springframework.security: TRACE